# Generated by Django 3.2.16 on 2024-02-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_start', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('mail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senderapp.mailinglist')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senderapp.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senderapp.recipient')),
            ],
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='message',
            field=models.ManyToManyField(blank=True, to='senderapp.Message'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='recipient',
            field=models.ManyToManyField(blank=True, to='senderapp.Recipient'),
        ),
    ]
